src/main/resources/jmix_list/html/list.jsp

https://jira.jahia.org/browse/QA-12386

QA-12386 : remove <div class="clear"> from default list view

---

src/main/resources/javascript/editableFile.display.js
src/main/resources/jnt_editableFile/html/editableFile.display.jsp
src/main/resources/resources/DefaultJahiaTemplates_de.properties
src/main/resources/resources/DefaultJahiaTemplates_en.properties
src/main/resources/resources/DefaultJahiaTemplates_es.properties
src/main/resources/resources/DefaultJahiaTemplates_fr.properties
src/main/resources/resources/DefaultJahiaTemplates_it.properties
src/main/resources/resources/DefaultJahiaTemplates_pt.properties

https://jira.jahia.org/browse/QA-11872
Allow users to download files when they are too large to display (default limit is 1MB)

QA-11872 add download button to the editable file view

---

pom.xml

https://jira.jahia.org/browse/QA-11872
I had to bump the version of the master, as I had to create a branch for the 7.3.5.0 compatibility of this module

QA-11872 prepare next iteration

---

src/main/resources/jnt_listSites/html/listSites.jsp

https://jira.jahia.org/browse/BACKLOG-12252

BACKLOG-12252 : renaming of editModeAccess permission

---

src/main/resources/META-INF/definitions.cnd
src/main/resources/jnt_gotoManager/html/gotoManager.jsp

https://jira.jahia.org/browse/BACKLOG-13313

BACKLOG-13313 : remove unecessary type and unecessary if conditions

---

src/main/resources/jnt_pager/html/pager.infinite.jsp

https://jira.jahia.org/browse/QA-13006

QA-13006 : fix pager inifinite scroll

---

pom.xml
src/main/resources/jmix_list/html/list.hidden.header.jsp

https://jira.jahia.org/browse/BACKLOG-13930

BACKLOG-13930: Optimize jsps

---

pom.xml

BACKLOG-14378 - Updated the scm tag to match the branch

---

pom.xml
src/main/resources/META-INF/definitions.cnd

https://jira.jahia.org/browse/QA-13309 
Remove news letter mixin

Qa 13309 Remove newsletter mixin

---

src/main/resources/jnt_addComment/html/addComment.jsp
src/main/resources/jnt_categorizing/html/categorizing.jsp
src/main/resources/jnt_createWebProject/html/createWebProject.jsp
src/main/resources/jnt_displayCategories/html/displayCategories.jsp
src/main/resources/jnt_editableFile/html/editableFile.display.jsp
src/main/resources/jnt_fileList/html/fileList.select.jsp
src/main/resources/jnt_fileList/html/fileList.wikiSelect.jsp
src/main/resources/jnt_fileUpload/html/fileUpload.jsp
src/main/resources/jnt_listSites/html/listSites.jsp
src/main/resources/jnt_manageRoles/html/manageRoles.flow/editRoleMembers.jsp
src/main/resources/jnt_manageRoles/html/manageRoles.flow/view.jsp
src/main/resources/jnt_manageRoles/html/manageRoles.settingsBootstrap3GoogleMaterialStyle.flow/editRoleMembers.jsp
src/main/resources/jnt_manageRoles/html/manageRoles.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp
src/main/resources/jnt_navMenuText/html/navMenuText.jsp
src/main/resources/jnt_pageFormCreation/html/pageFormCreation.jsp
src/main/resources/jnt_shortcuts/html/shortcuts.inline.jsp
src/main/resources/jnt_shortcuts/html/shortcuts.jsp
src/main/resources/jnt_topic/html/topic.jsp

https://jira.jahia.org/browse/BACKLOG-11183
Remove inline javascript

Backlog 11183 Remove inline javascript

---

.circleci/.circleci.settings.xml
.circleci/config.yml
.github/workflows/triggerCircleCIOnPR.yml

https://jira.jahia.org/browse/BACKLOG-11183
After the merge, cherrypick the config on the branch for 7.3 compatibility (7_6_x)

[BACKLOG-11183] Add the CircleCI build config

---

src/main/resources/jnt_fileList/html/fileList.select.jsp

https://jira.jahia.org/browse/BACKLOG-14988
Prevent default action on click

BACKLOG-14988 Prevent default action on click

---

src/main/resources/org/jahia/modules/defaultmodule/alert-publish-template.de.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-publish-template.en.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-publish-template.fr.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-publish-template.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-reject-template.de.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-reject-template.en.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-reject-template.fr.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-reject-template.mail
src/main/resources/org/jahia/modules/defaultmodule/start-publication-template.de.mail
src/main/resources/org/jahia/modules/defaultmodule/start-publication-template.en.mail
src/main/resources/org/jahia/modules/defaultmodule/start-publication-template.fr.mail
src/main/resources/org/jahia/modules/defaultmodule/start-publication-template.mail

https://jira.jahia.org/browse/BACKLOG-15073

BACKLOG-15073: Add workflowTitle in the template

---

src/main/resources/META-INF/definitions.cnd

https://jira.jahia.org/browse/BACKLOG-15213

BACKLOG-15213: deprecate and hide jnt:introduction

---

src/main/resources/resources/DefaultJahiaTemplates_de.properties
src/main/resources/resources/DefaultJahiaTemplates_es.properties
src/main/resources/resources/DefaultJahiaTemplates_it.properties
src/main/resources/resources/DefaultJahiaTemplates_pt.properties

https://jira.jahia.org/browse/QA-13536
Simple change to add the missing translation for DE, ES, IT, and PT.

QA-13536: Add-in translation for DE, ES, IT, and PT.

---

src/main/resources/jmix_list/html/list.hidden.header.jsp

https://jira.jahia.org/browse/BACKLOG-15364
Fix comment

BACKLOG-15364 Fix comment

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-15396
Updating the pom version from 7.7.1-SNAPSHOT to 7.8.0-SNAPSHOT.

BACKLOG-15396: changing the version of module from 7.7.1-SNAPSHOT to 7.8.0-SNAPSHOT

---

pom.xml
src/main/java/org/jahia/modules/defaultmodule/actions/MultipleDeleteAction.java
src/main/java/org/jahia/modules/defaultmodule/actions/MultiplePasteAction.java

https://jira.jahia.org/browse/QA-13595

QA-13595 Update pom and replace logger

---

pom.xml
src/main/java/org/jahia/modules/defaultmodule/RolesHandler.java

https://jira.jahia.org/browse/QA-13811
The system is in charge of merging with the users from the global level

QA-13811: As for groups use siteKey if in a site. 

---

src/main/java/org/jahia/modules/defaultmodule/RolesHandler.java

https://jira.jahia.org/browse/QA-13811
The system is in charge of merging with the users from the global level (#55)
(cherry picked from commit 5d84bc637d48b6cc7eb5977c14a57afcf6b0687a)

QA-13811: As for groups use siteKey if in a site.

---

pom.xml

https://jira.jahia.org/browse/QA-13999 
Use latest SNAPSHOT of the module-test-framework

QA-13999: Use latest SNAPSHOT of the module-test-framework

---

pom.xml

https://jira.jahia.org/browse/QA-14086
with the missing bridge between log4j and slf4j. This way we do not introduced conflicting version of log4j during the tests between 8.1.0.0 and 8.1.1.0-SNAPSHOT

QA-14086: Replace module-test-framework 8.1.1.0-SNAPSHOT 

---

pom.xml
src/main/import/repository.xml

https://jira.jahia.org/browse/TECH-1058
- Remove all "automatic" dependencies to default module
- Remove default dependency to default module in parent-module pom
- Remove dependency from default to assets
- Auto deploy assets on all sites

TECH-1058: Update dependencies

---

pom.xml

https://jira.jahia.org/browse/TECH-1058

TECH-1058: Update parent

---

README.md

https://jira.jahia.org/browse/TECH-1058

TECH-1058 - Update README.md

---

src/main/resources/jnt_addComment/html/addComment.jsp

https://jira.jahia.org/browse/BACKLOG-20886

BACKLOG-20886: Removed captcha

---

src/main/resources/jnt_addComment/html/addComment.jsp

https://jira.jahia.org/browse/TECH-1432
Replace jquery.validate with built-in html form validation

TECH-1432: Remove jquery validate

---

pom.xml

https://jira.jahia.org/browse/TECH-1416

TECH-1416: Fix guava imports

---

pom.xml

https://jira.jahia.org/browse/TECH-749
junit minor version upgrade to 4.13.2

TECH-749: junit minor version upgrade

---

src/main/resources/org/jahia/modules/defaultmodule/alert-publish-template.de.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-publish-template.en.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-publish-template.fr.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-publish-template.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-reject-template.de.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-reject-template.en.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-reject-template.fr.mail
src/main/resources/org/jahia/modules/defaultmodule/alert-reject-template.mail
src/main/resources/org/jahia/modules/defaultmodule/start-publication-template.de.mail
src/main/resources/org/jahia/modules/defaultmodule/start-publication-template.en.mail
src/main/resources/org/jahia/modules/defaultmodule/start-publication-template.fr.mail
src/main/resources/org/jahia/modules/defaultmodule/start-publication-template.mail

https://jira.jahia.org/browse/QA-15119

QA-15119: change target of the links in the publication mail

---

.github/maven.settings.xml
.github/workflows/on-release.yml

https://jira.jahia.org/browse/BACKLOG-23580

BACKLOG-23580: Added staging credentials and updated release workflow
